from __future__ import annotations

VID = 0x0483
PID = 0x5750

FRAME_START = 0x68
FRAME_END = 0x16
HOST_DIRECTION = 0x11
DEVICE_DIRECTION = 0x21
HEARTBEAT_COMMAND = 0x01
UPDATE_COMMAND = 0x05
KEY_STATUS_COMMAND = 0x0D
FLASH_ID_COMMAND = 0x0E
FLASH_SCAN_COMMAND = 0x0F
FLASH_TEST_COMMAND = 0x10
FLASH_STATUS_COMMAND = 0x11
FLASH_MODE_PROBE_COMMAND = 0x12
MOTOR_TEST_COMMAND = 0x13
MOTOR_TACHO_TEST_COMMAND = 0x14
MOTOR_STOP_TEST_COMMAND = 0x15
MOTOR_DUAL_TEST_COMMAND = 0x16
MOTOR_CONTROL_COMMAND = 0x17
INPUT_SENSOR_COMMAND = 0x18
DEVICE_STATUS_COMMAND = 0x19
MOTOR_TYPE_COMMAND = 0x1A
MOTOR_POSITION_COMMAND = 0x1B
MOTOR_SPEED_COMMAND = 0x1C
DEVICE_PROTOCOL_MAJOR = 1
DEVICE_PROTOCOL_MINOR = 5
DEVICE_CAPABILITY_UPDATE = 1 << 0
DEVICE_CAPABILITY_MOTOR_CONTROL = 1 << 1
DEVICE_CAPABILITY_MOTOR_TACHO = 1 << 2
DEVICE_CAPABILITY_INPUT_SENSOR = 1 << 3
DEVICE_CAPABILITY_BATTERY = 1 << 4
DEVICE_CAPABILITY_KEYS = 1 << 5
DEVICE_CAPABILITY_MOTOR_TYPE = 1 << 6
DEVICE_CAPABILITY_MOTOR_POSITION = 1 << 7
MOTOR_TEST_ACTION_STATUS = 0x00
MOTOR_TEST_ACTION_START = 0x01
MOTOR_TEST_ACTION_STOP = 0x02
MOTOR_CONTROL_ACTION_STATUS = 0x00
MOTOR_CONTROL_ACTION_SET_POWER = 0x01
MOTOR_CONTROL_ACTION_COAST = 0x02
MOTOR_CONTROL_ACTION_BRAKE = 0x03
MOTOR_CONTROL_ACTION_RESET_TACHO = 0x04
MOTOR_POSITION_ACTION_STATUS = 0x00
MOTOR_POSITION_ACTION_START = 0x01
MOTOR_POSITION_ACTION_STOP = 0x02
MOTOR_TYPE_ACTION_REFRESH = 0x01
MOTOR_SPEED_ACTION_STATUS = 0x00
MOTOR_SPEED_ACTION_START = 0x01
MOTOR_SPEED_ACTION_COAST = 0x02
MOTOR_SPEED_ACTION_BRAKE = 0x03
INPUT_SENSOR_ACTION_STATUS = 0x00
INPUT_SENSOR_ACTION_SET_MODE = 0x01
INPUT_SENSOR_ACTION_RESTART = 0x02
MOTOR_OUTPUT_COAST = 0x00
MOTOR_OUTPUT_DRIVE = 0x01
MOTOR_OUTPUT_BRAKE = 0x02

MAX_PAYLOAD = 1010
LEGACY_REPORT_SIZE = 64
HIGH_SPEED_REPORT_DATA_SIZE = 1024

HEARTBEAT_TIMEOUT_SECONDS = 2.0
KEY_STATUS_TIMEOUT_SECONDS = 2.0
FLASH_ID_TIMEOUT_SECONDS = 2.0
FLASH_DIAGNOSTIC_TIMEOUT_SECONDS = 5.0
MOTOR_TEST_TIMEOUT_SECONDS = 2.0
INPUT_SENSOR_TIMEOUT_SECONDS = 2.0
DEVICE_STATUS_TIMEOUT_SECONDS = 2.0
FIRST_PACKET_ACK_TIMEOUT_SECONDS = 15.0
PACKET_ACK_TIMEOUT_SECONDS = 4.0
HID_READ_TIMEOUT_MS = 250
HID_WRITE_TIMEOUT_MS = 2000
FRAGMENT_WRITE_DELAY_SECONDS = 0.003

SUPPORTED_FIRMWARE_HEADERS = (b"EST", b"APP=")
