#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

#define APP_FLASH_START                 0x08010000U
#define APP_FLASH_END                   0x08080000U
#define APP_FLASH_CAPACITY              (APP_FLASH_END - APP_FLASH_START)

#define UPDATE_FLASH_START              0x08080000U
#define UPDATE_FLASH_PHYSICAL_END       0x08100000U
#define UPDATE_MAX_PACKAGE_SIZE         APP_FLASH_CAPACITY

#define UPDATE_LENGTH_LOW_ADDRESS       0x0800C000U
#define UPDATE_LENGTH_HIGH_ADDRESS      0x0800C008U
#define UPDATE_STATUS_ADDRESS           0x0800C010U
#define UPDATE_STATUS_FLASH_SECTOR      3U
#define UPDATE_STATUS_PENDING           0x0000U

#define BOOTLOADER_MIN_STORED_LENGTH    (200U * 1024U)
#define RELEASE_PACKAGE_SIZE            (256U * 1024U)

#define UPDATE_COMMAND                  0x05U
#define HEARTBEAT_COMMAND               0x01U
#define KEY_STATUS_COMMAND              0x0DU
#define FLASH_ID_COMMAND                0x0EU
#define FLASH_SCAN_COMMAND              0x0FU
#define FLASH_TEST_COMMAND              0x10U
#define FLASH_STATUS_COMMAND            0x11U
#define FLASH_MODE_PROBE_COMMAND        0x12U
#define MOTOR_TEST_COMMAND              0x13U
#define MOTOR_TACHO_TEST_COMMAND        0x14U
#define MOTOR_STOP_TEST_COMMAND         0x15U
#define MOTOR_DUAL_TEST_COMMAND         0x16U
#define MOTOR_CONTROL_COMMAND           0x17U
#define INPUT_SENSOR_COMMAND            0x18U
#define DEVICE_STATUS_COMMAND           0x19U
#define MOTOR_TYPE_COMMAND              0x1AU
#define MOTOR_POSITION_COMMAND          0x1BU
#define MOTOR_SPEED_COMMAND             0x1CU
#define MOTOR_PAIR_POSITION_COMMAND     0x1DU
#define MOTOR_PAIR_SPEED_COMMAND        0x1EU
#define DRIVE_STRAIGHT_COMMAND          0x1FU
#define DRIVE_RUN_COMMAND               0x20U
#define DEVICE_PROTOCOL_MAJOR           1U
#define DEVICE_PROTOCOL_MINOR           9U
#define DEVICE_CAPABILITY_UPDATE        (1UL << 0U)
#define DEVICE_CAPABILITY_MOTOR_CONTROL (1UL << 1U)
#define DEVICE_CAPABILITY_MOTOR_TACHO   (1UL << 2U)
#define DEVICE_CAPABILITY_INPUT_SENSOR  (1UL << 3U)
#define DEVICE_CAPABILITY_BATTERY       (1UL << 4U)
#define DEVICE_CAPABILITY_KEYS          (1UL << 5U)
#define DEVICE_CAPABILITY_MOTOR_TYPE    (1UL << 6U)
#define DEVICE_CAPABILITY_MOTOR_POSITION (1UL << 7U)
#define DEVICE_CAPABILITY_MOTOR_PAIR_POSITION (1UL << 8U)
#define DEVICE_CAPABILITY_MOTOR_PAIR_SPEED (1UL << 9U)
#define DEVICE_CAPABILITY_DRIVE_STRAIGHT (1UL << 10U)
#define DEVICE_CAPABILITY_DRIVE_RUN     (1UL << 11U)
#define MOTOR_TEST_ACTION_STATUS        0x00U
#define MOTOR_TEST_ACTION_START         0x01U
#define MOTOR_TEST_ACTION_STOP          0x02U
#define MOTOR_CONTROL_ACTION_STATUS     0x00U
#define MOTOR_CONTROL_ACTION_SET_POWER  0x01U
#define MOTOR_CONTROL_ACTION_COAST      0x02U
#define MOTOR_CONTROL_ACTION_BRAKE      0x03U
#define MOTOR_CONTROL_ACTION_RESET_TACHO 0x04U
#define MOTOR_POSITION_ACTION_STATUS    0x00U
#define MOTOR_POSITION_ACTION_START     0x01U
#define MOTOR_POSITION_ACTION_STOP      0x02U
#define MOTOR_TYPE_ACTION_REFRESH       0x01U
#define MOTOR_SPEED_ACTION_STATUS       0x00U
#define MOTOR_SPEED_ACTION_START        0x01U
#define MOTOR_SPEED_ACTION_COAST        0x02U
#define MOTOR_SPEED_ACTION_BRAKE        0x03U
#define MOTOR_PAIR_POSITION_ACTION_STATUS 0x00U
#define MOTOR_PAIR_POSITION_ACTION_START 0x01U
#define MOTOR_PAIR_POSITION_ACTION_STOP 0x02U
#define MOTOR_PAIR_SPEED_ACTION_STATUS  0x00U
#define MOTOR_PAIR_SPEED_ACTION_START   0x01U
#define MOTOR_PAIR_SPEED_ACTION_COAST   0x02U
#define MOTOR_PAIR_SPEED_ACTION_BRAKE   0x03U
#define DRIVE_STRAIGHT_ACTION_STATUS    0x00U
#define DRIVE_STRAIGHT_ACTION_START     0x01U
#define DRIVE_STRAIGHT_ACTION_STOP      0x02U
#define DRIVE_RUN_ACTION_STATUS         0x00U
#define DRIVE_RUN_ACTION_START          0x01U
#define DRIVE_RUN_ACTION_STOP           0x02U
#define DRIVE_RUN_MODE_DEGREES          0x00U
#define DRIVE_RUN_MODE_TIME_MS          0x01U
#define INPUT_SENSOR_ACTION_STATUS      0x00U
#define INPUT_SENSOR_ACTION_SET_MODE    0x01U
#define INPUT_SENSOR_ACTION_RESTART     0x02U
#define HOST_FRAME_DIRECTION            0x11U
#define DEVICE_FRAME_DIRECTION          0x21U
#define FRAME_START_BYTE                0x68U
#define FRAME_END_BYTE                  0x16U
#define UPDATE_FRAME_MAX_PAYLOAD        1010U
#define UPDATE_FRAME_MAX_DATA_LENGTH    (UPDATE_FRAME_MAX_PAYLOAD + 4U)
#define UPDATE_FRAME_MAX_LENGTH         (UPDATE_FRAME_MAX_DATA_LENGTH + 7U)
#define UPDATE_SESSION_TIMEOUT_MS       400000U
#define LOGICAL_FRAME_TIMEOUT_MS        3000U
#define LOGICAL_FRAME_RESTART_GAP_MS    250U
#define FINAL_ACK_POWER_OFF_TIMEOUT_MS  1000U

#define USB_VENDOR_ID                   0x0483U
#define USB_PRODUCT_ID                  0x5750U
#define USB_HID_IN_ENDPOINT             0x82U
#define USB_HID_OUT_ENDPOINT            0x01U
#define USB_HID_REPORT_SIZE             1024U

#define EXTERNAL_FLASH_TEST_ADDRESS     0x01FFF000U

#ifndef APP_VERSION_TEXT
#define APP_VERSION_TEXT "M0.01A"
#endif

_Static_assert(sizeof(APP_VERSION_TEXT) == 7U,
	"APP_VERSION_TEXT must contain exactly six ASCII characters");
_Static_assert(RELEASE_PACKAGE_SIZE > (BOOTLOADER_MIN_STORED_LENGTH + 1U),
	"Release package does not satisfy the old Bootloader minimum length");
_Static_assert(RELEASE_PACKAGE_SIZE < UPDATE_MAX_PACKAGE_SIZE,
	"Release package does not fit the old Bootloader APP range");

#endif
