#ifndef EST_UI_TEXT_H
#define EST_UI_TEXT_H

#include <stdbool.h>
#include <stdint.h>

#include "est_types.h"
#include "est_ui_font.h"

typedef enum {
	EST_UI_LANGUAGE_CHINESE = 0,
	EST_UI_LANGUAGE_ENGLISH = 1,
	EST_UI_LANGUAGE_PORTUGUESE = 2,
	EST_UI_LANGUAGE_COUNT = 3
} est_ui_language_t;

typedef enum {
	EST_UI_STRING_HOME_RECENT_EMPTY = 0,
	EST_UI_STRING_HOME_RECENT_LABEL,
	EST_UI_STRING_HOME_PROGRAMS,
	EST_UI_STRING_HOME_PORTS,
	EST_UI_STRING_HOME_REMOTE,
	EST_UI_STRING_HOME_MOTOR,
	EST_UI_STRING_HOME_SETTINGS,
	EST_UI_STRING_POWER_TITLE,
	EST_UI_STRING_POWER_BODY,
	EST_UI_STRING_POWER_CANCEL_HINT,
	EST_UI_STRING_POWER_CONFIRM_HINT,
	EST_UI_STRING_PROGRAMS_TITLE,
	EST_UI_STRING_PROGRAMS_EMPTY,
	EST_UI_STRING_PROGRAMS_LOADING,
	EST_UI_STRING_DELETE_TITLE,
	EST_UI_STRING_DELETE_IRREVERSIBLE,
	EST_UI_STRING_CANCEL,
	EST_UI_STRING_DELETE,
	EST_UI_STRING_DELETE_HINT,
	EST_UI_STRING_RUNNING,
	EST_UI_STRING_PORTS_TITLE,
	EST_UI_STRING_MOTORS,
	EST_UI_STRING_SENSORS,
	EST_UI_STRING_DEVICE,
	EST_UI_STRING_STATE,
	EST_UI_STRING_VALUE,
	EST_UI_STRING_DISCONNECTED,
	EST_UI_STRING_DETECTING,
	EST_UI_STRING_STOPPED,
	EST_UI_STRING_ACTIVE,
	EST_UI_STRING_BRAKING,
	EST_UI_STRING_LARGE_MOTOR,
	EST_UI_STRING_MEDIUM_MOTOR,
	EST_UI_STRING_SETTINGS_TITLE,
	EST_UI_STRING_BACKLIGHT,
	EST_UI_STRING_VOLUME,
	EST_UI_STRING_LANGUAGE,
	EST_UI_STRING_CHINESE,
	EST_UI_STRING_PORTUGUESE,
	EST_UI_STRING_DEVICE_INFO,
	EST_UI_STRING_MODEL,
	EST_UI_STRING_FIRMWARE,
	EST_UI_STRING_BOOTLOADER,
	EST_UI_STRING_USB,
	EST_UI_STRING_BATTERY,
	EST_UI_STRING_CONNECTED,
	EST_UI_STRING_LOW_BATTERY,
	EST_UI_STRING_STORAGE_ERROR,
	EST_UI_STRING_PROGRAM_LIST_UNREADABLE,
	EST_UI_STRING_PROGRAM_UNREADABLE,
	EST_UI_STRING_PROGRAM_STOPPED,
	EST_UI_STRING_MOTORS_SAFE,
	EST_UI_STRING_CHARGE_BEFORE_RUN,
	EST_UI_STRING_RETRY,
	EST_UI_STRING_REMOTE_TITLE,
	EST_UI_STRING_REMOTE_CONNECT_IR,
	EST_UI_STRING_REMOTE_SIGNAL_LOST,
	EST_UI_STRING_REMOTE_DEVICE_LOST,
	EST_UI_STRING_REMOTE_BRAKE_ALL,
	EST_UI_STRING_MOTOR_OUTPUT_TITLE,
	EST_UI_STRING_MOTOR_STOP,
	EST_UI_STRING_MOTOR_FORWARD,
	EST_UI_STRING_MOTOR_REVERSE,
	EST_UI_STRING_MOTOR_POWER,
	EST_UI_STRING_RECEIVING_PROGRAM,
	EST_UI_STRING_POWER_OFF_SHORT,
	EST_UI_STRING_COUNT
} est_ui_string_id_t;

const char *est_ui_text(est_ui_language_t language,
	est_ui_string_id_t string_id);
uint16_t est_ui_text_width(est_ui_language_t language,
	est_ui_string_id_t string_id, est_ui_text_style_t style);
est_result_t est_ui_text_draw(uint16_t x, uint16_t y,
	est_ui_language_t language, est_ui_string_id_t string_id,
	est_ui_text_style_t style);
est_result_t est_ui_text_draw_raw(uint16_t x, uint16_t y,
	const char *text, est_ui_text_style_t style);

#endif
