#ifndef EST_TYPES_H
#define EST_TYPES_H

#include <stdint.h>

typedef enum {
	EST_OK = 0,
	EST_ERR_INVALID_ARGUMENT = -1,
	EST_ERR_INVALID_PORT = -2,
	EST_ERR_NOT_CONNECTED = -3,
	EST_ERR_TYPE_MISMATCH = -4,
	EST_ERR_NOT_SUPPORTED = -5,
	EST_ERR_BUSY = -6,
	EST_ERR_TIMEOUT = -7,
	EST_ERR_IO = -8,
	EST_ERR_STATE = -9
} est_result_t;

typedef enum {
	EST_MOTOR_PORT_A = 0,
	EST_MOTOR_PORT_B = 1,
	EST_MOTOR_PORT_C = 2,
	EST_MOTOR_PORT_D = 3,
	EST_MOTOR_PORT_COUNT = 4
} est_motor_port_t;

typedef enum {
	EST_SENSOR_PORT_1 = 0,
	EST_SENSOR_PORT_2 = 1,
	EST_SENSOR_PORT_3 = 2,
	EST_SENSOR_PORT_4 = 3,
	EST_SENSOR_PORT_COUNT = 4
} est_sensor_port_t;

typedef enum {
	EST_STOP_COAST = 0,
	EST_STOP_BRAKE = 1,
	EST_STOP_HOLD = 2
} est_stop_mode_t;

typedef enum {
	EST_MOTOR_TYPE_NONE = 0,
	EST_MOTOR_TYPE_LARGE = 4,
	EST_MOTOR_TYPE_MEDIUM = 5,
	EST_MOTOR_TYPE_UNKNOWN = 0xFF
} est_motor_type_t;

typedef enum {
	EST_SENSOR_TYPE_NONE = 0x00,
	EST_SENSOR_TYPE_SOUND = 0x03,
	EST_SENSOR_TYPE_TEMPERATURE = 0x06,
	EST_SENSOR_TYPE_TOUCH = 0x10,
	EST_SENSOR_TYPE_COLOR = 0x1D,
	EST_SENSOR_TYPE_ULTRASONIC = 0x1E,
	EST_SENSOR_TYPE_GYRO = 0x20,
	EST_SENSOR_TYPE_INFRARED = 0x21,
	EST_SENSOR_TYPE_UNKNOWN = 0xFF
} est_sensor_type_t;

typedef enum {
	EST_SENSOR_MODE_REFLECTED = 0,
	EST_SENSOR_MODE_GYRO_ANGLE = 0,
	EST_SENSOR_MODE_SOUND_DB = 0,
	EST_SENSOR_MODE_IR_PROXIMITY = 0,
	EST_SENSOR_MODE_DISTANCE_CM = 0,
	EST_SENSOR_MODE_CELSIUS = 0,
	EST_SENSOR_MODE_AMBIENT = 1,
	EST_SENSOR_MODE_GYRO_RATE = 1,
	EST_SENSOR_MODE_IR_BEACON = 1,
	EST_SENSOR_MODE_DISTANCE_INCH = 1,
	EST_SENSOR_MODE_FAHRENHEIT = 1,
	EST_SENSOR_MODE_COLOR = 2,
	EST_SENSOR_MODE_IR_REMOTE = 2,
	EST_SENSOR_MODE_PRESENCE = 2
} est_sensor_mode_t;

typedef enum {
	EST_SENSOR_DISCONNECTED = 0,
	EST_SENSOR_SYNCING = 1,
	EST_SENSOR_STREAMING = 2,
	EST_SENSOR_STALE = 3,
	EST_SENSOR_ERROR = 4
} est_sensor_state_t;

typedef enum {
	EST_VALUE_NONE = 0,
	EST_VALUE_BOOLEAN = 1,
	EST_VALUE_PERCENT = 2,
	EST_VALUE_INTEGER = 3,
	EST_VALUE_FIXED_TENTHS = 4,
	EST_VALUE_MILLIMETERS = 5,
	EST_VALUE_DEGREES = 6,
	EST_VALUE_DEGREES_PER_SECOND = 7,
	EST_VALUE_CELSIUS_TENTHS = 8,
	EST_VALUE_ENUM = 9
} est_value_format_t;

#endif
