#!/usr/bin/env python3
"""Generate the small EST OS CJK bitmap subset used by the device menu."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


GLYPHS = """暂无最近程序端口设置确认关机是否关闭返回取消删除运行中查看马达传感器设备状态数值未连接识别停止制动大型中型背光音量语言中文信息型号固件引导电量已低存储错误列表法读取安全充后再重试检测百分比异常遥控红外请到信号丢失正转反功率输出"""
GLYPHS += "\u4f5c\u5728\u590d\u6062\u64cd\u6709\u6ca1\u6b63"


def unique_glyphs() -> list[str]:
    return sorted(set(GLYPHS), key=ord)


def render_glyph(font: ImageFont.FreeTypeFont, character: str) -> list[int]:
    canvas = Image.new("L", (16, 16), 0)
    draw = ImageDraw.Draw(canvas)
    bounds = draw.textbbox((0, 0), character, font=font)
    width = bounds[2] - bounds[0]
    height = bounds[3] - bounds[1]
    x = (16 - width) // 2 - bounds[0]
    y = (16 - height) // 2 - bounds[1]
    draw.text((x, y), character, font=font, fill=255)

    rows: list[int] = []
    for row in range(16):
        value = 0
        for column in range(16):
            if canvas.getpixel((column, row)) >= 96:
                value |= 1 << (15 - column)
        rows.append(value)
    return rows


def generate(font_path: Path, output_path: Path) -> None:
    font = ImageFont.truetype(str(font_path), 15)
    digest = hashlib.sha256(font_path.read_bytes()).hexdigest()
    lines = [
        "/* Generated by tools/generate_ui_font.py.",
        " * Source: Noto Sans CJK SC Regular (SIL Open Font License 1.1).",
        f" * Source SHA-256: {digest}",
        " */",
        '#include "est_ui_font_data.h"',
        "",
        "const est_ui_font_glyph_t est_ui_font_glyphs[] = {",
    ]
    for character in unique_glyphs():
        rows = render_glyph(font, character)
        values = ", ".join(f"0x{value:04X}U" for value in rows)
        lines.append(f"\t{{0x{ord(character):04X}U, {{{values}}}}},")
    lines.extend(
        [
            "};",
            "",
            "const size_t est_ui_font_glyph_count =",
            "\tsizeof(est_ui_font_glyphs) / sizeof(est_ui_font_glyphs[0]);",
            "",
        ]
    )
    output_path.write_text("\n".join(lines), encoding="ascii")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    generate(args.font, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
